Removing json-serilization of params
Passing serialized dictionary objects as params fails on older versions of requests. This is because requests is unable to recognise that the strings are already serialized, resulting in a ValueError:

ValueError: cannot encode objects that are not 2-tuples

If passed a dict, requests will perform the serialization itself:

:param params: (optional) Dictionary or bytes to be sent in the query string for the :class:`Request`.